fm_elfinder:
    instances:
        default:
            locale: fr
            editor: ckeditor
            connector:
                debug: false
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: images/ckeditor
                        show_hidden: false

